/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package minijuego;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author kevin2
 */
public final class VtnMensaje extends javax.swing.JFrame {

    //Variable para guardar el mensaje
    String mensaje = " ";
    //Variable para guardar  el puntaje
    int puntaje = 0;

    /**
     * Creates new form VtnMensaje
     *
     * Constructor
     *
     * @param mensaje que sera el mensaje que se mostrara. 1.Perder 2.Perder una
     * vida 3.Ganar
     * @param puntaje es el puntaje obtenido cada vez que se pierde una vida o
     * el juego
     */
    public VtnMensaje(String mensaje, int puntaje) {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Icono.png"));
        this.setIconImage(icono);
        initComponents();
        this.mensaje = mensaje;
        this.puntaje = puntaje;
        abrirMensaje();
    }

    /**
     * Metodo que permite mostrar el mensaje Si se perdio una vida no muestres
     * el mensaje de Fin del juego Sino muestra el mensaje si se ha terminado
     */
    public void abrirMensaje() {
        if ("Perdiste una vida".equals(this.mensaje)) {
            jLabel1.setVisible(false);
            if(InterfazPacman.clip.isOpen()){
                   InterfazPacman.clip.close();
                   
                   InterfazPacman.sonidos(InterfazPacman.muerte);
                }
        } else if (Pacman.noPastillas == 0) {
            jLabel1.setText("¡Ganaste!");

                if(InterfazPacman.clip.isOpen()){
                   InterfazPacman.clip.close();
                   InterfazPacman.sonidos(InterfazPacman.gana);
                }
        }

        lblMensaje.setText(this.mensaje);
        lblPuntaje.setText(this.puntaje + " puntos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblPuntaje = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¡Fin del juego!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 590, 40));

        jButton1.setBackground(new java.awt.Color(0, 51, 102));
        jButton1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aceptar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 131, 40));

        lblPuntaje.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblPuntaje.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(lblPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 270, 34));

        lblMensaje.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(204, 204, 204));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 480, 40));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Puntaje:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 112, 34));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton de aceptar el mensjae leido Cierra la ventana una vez que es
     * presionado
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (InterfazPacman.clip.isOpen()) {
            InterfazPacman.clip.close();
            InterfazPacman.sonidoFondo(InterfazPacman.sonidoInicial);
        }else{
            InterfazPacman.sonidoFondo(InterfazPacman.sonidoInicial);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblPuntaje;
    // End of variables declaration//GEN-END:variables
}
